### PR TITLE
fix(kani): unblock the proof build on Kani 0.68.0's std shim

### PR DESCRIPTION
**Pull request by norrietaylor**
## Summary

The nightly `kani-canary` job has failed on the last three `nightly-tests` runs (tracked in [#1402](https://github.com/gominimal/minimal/issues/1402)) with:

```
   Compiling backtrace v0.3.76
error[E0659]: `unreachable` is ambiguous
   --> backtrace-0.3.76/src/types.rs:74:9
```

**Root cause.** Kani compiles every crate against its own `std` shim, which exports Kani's `assert!`/`panic!`/`unreachable!` at the shim crate root. Kani 0.68.0 gave that shim a `prelude` module that forwards to real std's prelude without those overrides ([model-checking/kani#4666](https://github.com/model-checking/kani/pull/4666)). `backtrace` is `#![no_std]` and does both `#[macro_use] extern crate std;` and `use std::prelude::v1::*;`, so one call site now resolves two different `unreachable!` macros. Kani 0.67.0's shim had no `prelude` module, which is why the pinned `ci-kani` lane stays green. This is not a rustc regression: the same nightly compiles `backtrace` cleanly outside Kani.

**Why not a dependency bump.** `backtrace` 0.3.76 is the newest release and upstream master still has the unqualified call. `backtrace` reaches the kernel crates through `nickel-lang-core` → `topiary-core` → `miette[fancy]`, with no feature or version lever. Kani's `--no-assert-overrides` does not help (verified): it suppresses injection into local crates, not the shim's exports.

**Fix.** `scripts/kani.sh` already builds from a scratch copy of the workspace. This adds a block that vendors `backtrace` once into the persisted target dir, qualifies the one call to `core::unreachable!` (the same macro, so no proof changes meaning), and adds it under the existing `[patch.crates-io]` table of the scratch copy. It self-disables when a fixed `backtrace` ships. No change to `.github/`, `Cargo.toml`, or `Cargo.lock`.

## Verification

Run locally on macOS arm64 with Kani installed for this task:

| Check | Result |
|---|---|
| CI failure reproduced on Kani 0.68.0 (bundled `nightly-2026-08-21`) | identical E0659 |
| `./scripts/kani.sh` on Kani 0.68.0 with this fix | exit 0, `sessions` 6/6 and `rcache` 3/3 harnesses verified |
| `./scripts/kani.sh` on the pinned Kani 0.67.0 with this fix | exit 0, same 6/6 and 3/3 |
| `sh -n`, `dash -n`, `shellcheck -s sh` on the script | clean |

Not verified on Linux; the block is POSIX sh with no platform paths, and the nightly run will be the proof.

## Follow-ups (not in this PR)

- Kani 0.68.0 bundles a toolchain above the workspace `rust-version` floor, so the script's MSRV scratch-copy workaround becomes deletable once `KANI_VERSION` moves to 0.68.0+. The proofs verify identically there.
- The script reports any compile failure as "vacuous or failing lane", which misdiagnosed this for three nights. A compile-vs-proof branch on the message would help.
- Worth an upstream issue on `model-checking/kani` and a one-token PR to `backtrace-rs`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: scripts/kani.sh [hunk 1]
```diff
@@ -39,6 +39,60 @@ rsync -a --exclude target --exclude .git --exclude .claude --exclude .scratch \
...
+btver="$(sed -n '/^name = "backtrace"$/{n;s/^version = "\(.*\)"$/\1/p;}' "$ws/Cargo.lock")"
+btsrc=""
+for d in "${CARGO_HOME:-$HOME/.cargo}"/registry/src/*/backtrace-"$btver"; do
+    if [ -d "$d" ]; then
+        btsrc="$d"
+        break
+    fi
+done
+if [ -n "$btver" ] && [ -n "$btsrc" ] &&
+    grep -q '^        unreachable!()$' "$btsrc/src/types.rs"; then
```
[the remark this answers is not in the document]
Comment (norrietaylor) [reply scripts/kani.sh:89]: Valid, and worse in CI than the finding says. Fixed in cfedb9fe.

You are right that no cargo runs before the glob — the first is the `cargo kani` inside `expect()`. But the lane does not self-heal after one warm-up run either: `.github/actions/setup-rust` uses `Swatinem/rust-cache`, whose `cleanRegistry` deletes every `registry/src/<index>/<pkg>` entry except `-sys` crates before saving, keeping only `registry/cache/*.crate` (cleanup.ts at the pinned `e18b4977` — *"`.cargo/registry/src` — Cargo usually re-creates these from the `.crate` cache below"*). So `backtrace-0.3.76` is unpacked by `cargo kani` itself, always after the glob, and the restored cache never carries it. On that path the block no-ops on **every** ci-kani run and the lane dies with the E0659 this PR exists to remove.

Both halves of your suggestion, then:

- `(cd "$ws" && cargo fetch)` before the version read. Verified that `cargo fetch` extracts rather than only downloading: with an empty `CARGO_HOME` and a one-dep crate on `backtrace = "0.3"`, `registry/src/index.crates.io-*/backtrace-0.3.76/` exists afterwards, not just the `.crate`. It also settles `Cargo.lock` before `btver` is read out of it.
- an `elif` that prints `WARNING: backtrace-$btver not unpacked in the cargo registry — E0659 workaround SKIPPED` when the version resolves but the glob still misses, so a skip can never be silent again. The self-disable path (source found, `grep` no longer matching because a fixed `backtrace` shipped) stays quiet, as intended.

Verification on this machine, Kani 0.68.0 / CBMC 6.11.0: `./scripts/kani.sh` exit 0, `Complete - 6 successfully verified harnesses` (sessions) and `Complete - 3 successfully verified harnesses` (rcache), with `target/kani/kani-vendor/backtrace-0.3.76/src/types.rs:74` carrying `core::unreachable!()` and no warning emitted. `sh -n`, `dash -n`, `shellcheck -s sh` clean.

[the remark this answers is not in the document]
Comment (norrietaylor) [reply scripts/kani.sh:89]: Follow-up, now that both ci-kani runs of this branch exist on Linux — the CI evidence confirms your finding exactly:

- **Before the fix** (`a894dab9`, [run 35316063891](https://github.com/gominimal/minimal/actions/runs/35316063891)): the string `backtrace` appears **zero** times in the whole `kani` job log. No vendored copy was built, so the `[patch.crates-io]` entry was never added — cargo reused the registry-built artifact restored from main's cache. A path-source patch produces a different package id, so it could not have reused that artifact had the block fired. The workaround no-opped, exactly as predicted.
- **After the fix** (`cfedb9fe`, [run 35326253652](https://github.com/gominimal/minimal/actions/runs/35326253652)): `cargo fetch` runs (`Updating crates.io index`), no `WARNING:` line, and the proof build reports `Compiling backtrace v0.3.76 (/home/runner/work/minimal/minimal/target/kani/kani-vendor/backtrace-0.3.76)` — the patched copy. Lane green in 2m31s, 6/6 and 3/3.

So on 0.67.0 this was invisible; the moment the pin moves to 0.68.0 in #1435 it would have been the E0659 failure again. Thanks — this was the difference between the fix working in CI and only on my laptop.

File: scripts/kani.sh [hunk 2]
```diff
@@ -39,6 +39,74 @@ rsync -a --exclude target --exclude .git --exclude .claude --exclude .scratch \
...
+    grep -q '^backtrace = { path = ' "$ws/Cargo.toml" || {
+        echo "FATAL: no [patch.crates-io] table to carry the backtrace E0659 workaround" >&2
+        exit 1
+    }
+elif [ -n "$btver" ] && [ -z "$btsrc" ]; then
+    # Unreachable after the fetch above, so say so out loud rather than
+    # skipping mutely: a lane that then fails on E0659 is one read from
+    # diagnosed instead of three nights of guessing.
+    echo "WARNING: backtrace-$btver not unpacked in the cargo registry — E0659 workaround SKIPPED" >&2
+fi
```
[the remark this answers is not in the document]
Comment (norrietaylor) [reply scripts/kani.sh:123]: Right, and a fair hit on the previous commit: I put the warning on the branch the `cargo fetch` had just made unreachable and left the reachable one silent. Fixed in c67763ed.

A second `elif` now covers source-present-but-pattern-missed. It names both futures that land there, because the log genuinely cannot tell them apart:

```
NOTE: backtrace-$btver no longer matches the patched call site — E0659 workaround not applied;
delete this block if upstream fixed it, widen the pattern if the proof build now fails on E0659
```

Deliberately a NOTE rather than a WARNING: when upstream does fix the call, this is the expected path and the line is the "delete me" nudge the block's comment already asks for, not an alarm.

The gate itself is untouched — same condition, same vendoring — so this is message-branch only. All four states exercised under `sh` and `dash`:

| btver | source | call site matches | outcome |
|---|---|---|---|
| set | found | yes | workaround applied, silent |
| set | missing | — | `WARNING` (not unpacked) |
| set | found | no | `NOTE` (call site moved or fixed) |
| empty | — | — | silent: backtrace is out of the graph |

`sh -n`, `dash -n`, `shellcheck -s sh` clean; `./scripts/kani.sh` on Kani 0.68.0 still 6/6 (sessions) and 3/3 (rcache).

File: scripts/kani.sh [hunk 3]
```diff
@@ -39,6 +39,80 @@ rsync -a --exclude target --exclude .git --exclude .claude --exclude .scratch \
...
+        rm -f "$vendor.tmp/src/types.rs.kani-bak"
+        mv "$vendor.tmp" "$vendor"
+    fi
+    # awk, not sed: appending under the existing [patch.crates-io] needs a
+    # newline in the replacement, which BSD sed does not honour.
+    awk -v p="$vendor" '
+        { print }
+        /^\[patch\.crates-io\]$/ && !done { print "backtrace = { path = \"" p "\" }"; done = 1 }
+    ' "$ws/Cargo.toml" >"$ws/Cargo.toml.kani"
+    mv "$ws/Cargo.toml.kani" "$ws/Cargo.toml"
```
[the remark this answers is not in the document]
Comment (norrietaylor) [reply scripts/kani.sh:107]: Valid — reproduced it before touching anything. Fixed in 4a0e41ef.

`CARGO_TARGET_DIR=target/kani ./scripts/kani.sh` on the previous commit:

```
error: patch location `/private/var/folders/.../T/kani-ws.vkBdhR/target/kani/kani-vendor/backtrace-0.3.76`
       does not contain packages matching `backtrace`
help: check `backtrace` patch definition for `https://github.com/rust-lang/crates.io-index`
      in `/private/var/folders/.../T/kani-ws.vkBdhR/Cargo.toml`
FATAL: expected 6 verified harnesses in sessions — vacuous or failing lane
```

Exactly your reading: the vendor dir is created relative to the invocation directory, the patch path is resolved relative to the scratch manifest, and the two disagree — with the wrong message on top, which is the failure mode this PR exists to remove.

Normalized at the point you suggested, before anything embeds the value:

```sh
case "$CARGO_TARGET_DIR" in
    /*) ;;
    *) CARGO_TARGET_DIR="$PWD/$CARGO_TARGET_DIR" ;;
esac
export CARGO_TARGET_DIR
```

Side benefit: the "build artifacts land in the REAL workspace's target dir" comment right above it is now true for a relative override too, where before the artifacts went into the scratch copy and were deleted with it.

Verified: `CARGO_TARGET_DIR=target/kani ./scripts/kani.sh` exits 0 with `Complete - 6 successfully verified harnesses` (sessions) and `Complete - 3 successfully verified harnesses` (rcache); `sh -n`, `dash -n`, `shellcheck -s sh` clean.

**Review by bryan-minimal — APPROVED** [review]
